# Generated by Django 5.2.1 on 2025-05-25 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empleado', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido_empleado', models.CharField(blank=True, max_length=50, null=True)),
                ('sexo_empleado', models.IntegerField(blank=True, null=True)),
                ('telefono_empleado', models.CharField(blank=True, max_length=50, null=True)),
                ('email_empleado', models.CharField(blank=True, max_length=50, null=True)),
                ('profesion_empleado', models.CharField(blank=True, max_length=50, null=True)),
                ('foto_empleado', models.TextField(blank=True, null=True)),
                ('salario_empleado', models.BigIntegerField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, null=True)),
                ('documento', models.BigIntegerField()),
            ],
            options={
                'db_table': 'tbl_empleados',
            },
        ),
        migrations.CreateModel(
            name='LoginUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_user', models.DateTimeField(auto_now_add=True)),
                ('id_user', models.CharField(max_length=10)),
                ('tipo', models.CharField(max_length=10)),
                ('ip', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'login_user',
            },
        ),
        migrations.CreateModel(
            name='SolicitudCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo_original', models.CharField(max_length=255)),
                ('cantidad_paginas_original', models.IntegerField()),
                ('cantidad_comprobantes_separados', models.IntegerField()),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('cargado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(default='Completado', max_length=50)),
                ('errores_detectados', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'solicitudes_carga',
            },
        ),
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion_empleado', models.CharField(max_length=50)),
                ('nombre_empleado', models.CharField(max_length=255)),
                ('fecha_comprobante', models.DateField()),
                ('mes_periodo', models.CharField(max_length=7)),
                ('ruta_almacenamiento', models.CharField(max_length=500)),
                ('nombre_archivo_generado', models.CharField(max_length=255)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('id_solicitud', models.ForeignKey(db_column='id_solicitud', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.solicitudcarga')),
            ],
            options={
                'db_table': 'comprobantes',
            },
        ),
    ]
