# Generated by Django 5.2.1 on 2025-05-26 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '000X_huella_comprobante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huellacomprobante',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
