# Generated by Django 5.2.1 on 2025-05-28 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empleado', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido_empleado', models.CharField(blank=True, max_length=50, null=True)),
                ('sexo_empleado', models.IntegerField(blank=True, null=True)),
                ('telefono_empleado', models.CharField(blank=True, max_length=50, null=True)),
                ('email_empleado', models.CharField(blank=True, max_length=50, null=True)),
                ('profesion_empleado', models.CharField(blank=True, max_length=50, null=True)),
                ('foto_empleado', models.TextField(blank=True, null=True)),
                ('salario_empleado', models.BigIntegerField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, null=True)),
                ('documento', models.BigIntegerField()),
            ],
            options={
                'db_table': 'tbl_empleados',
            },
        ),
        migrations.CreateModel(
            name='LoginUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_user', models.DateTimeField(auto_now_add=True)),
                ('id_user', models.CharField(max_length=10)),
                ('tipo', models.CharField(max_length=10)),
                ('ip', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'login_user',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cesion', models.DateField(blank=True, null=True)),
                ('fecha_act', models.DateField(blank=True, null=True)),
                ('documento', models.CharField(max_length=30)),
                ('referencia', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_documento', models.CharField(blank=True, max_length=30, null=True)),
                ('nombre_completo', models.CharField(max_length=150)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('dias_mora_originador', models.FloatField(default=0)),
                ('dias_mora_caso_sas', models.FloatField(default=0)),
                ('total_dias_mora', models.FloatField(default=0)),
                ('anios_mora', models.FloatField(default=0)),
                ('principal', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('deuda_principal_k', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('intereses', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('tecnologia', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('seguro', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('otros_cargos', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('total_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('dcto_pago_contado_50', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('dcto_pago_contado_70_max_30', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('deuda_total', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('telefono_celular', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('celular_1', models.CharField(blank=True, max_length=20, null=True)),
                ('celular_2', models.CharField(blank=True, max_length=20, null=True)),
                ('celular_3', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion_1', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion_2', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion_3', models.CharField(blank=True, max_length=255, null=True)),
                ('email_1', models.CharField(blank=True, max_length=100, null=True)),
                ('email_2', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_1', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono_2', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='Activo', max_length=20)),
            ],
            options={
                'db_table': 'clientes',
                'unique_together': {('documento', 'referencia')},
            },
        ),
    ]
