# Generated by Django 5.2.1 on 2025-05-26 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_alter_huellacomprobante_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprobante',
            name='ruta_almacenamiento',
        ),
        migrations.AddField(
            model_name='comprobante',
            name='archivo_comprobante',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='comprobantes/'),
        ),
    ]
