# Generated by Django 5.2.1 on 2025-05-28 03:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente'},
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='anios_mora',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='celular_3',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='dcto_pago_contado_50',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='dcto_pago_contado_70_max_30',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='deuda_principal_k',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='deuda_total',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='dias_mora_caso_sas',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='dias_mora_originador',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='direccion_3',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='email_1',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='email_2',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='fecha_act',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='fecha_cesion',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='intereses',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='otros_cargos',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='principal',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='seguro',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='tecnologia',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='telefono_1',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='telefono_2',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='telefono_celular',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='total_dias_mora',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='total_pagado',
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_contrato',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Contrato'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='limite_credito',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Límite de Crédito'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='observaciones_adicionales',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones Adicionales'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.CharField(choices=[('Persona Natural', 'Persona Natural'), ('Empresa', 'Empresa'), ('Gobierno', 'Gobierno'), ('Otro', 'Otro')], default='Persona Natural', max_length=50, verbose_name='Tipo de Cliente'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ultima_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Asociado'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='valor_contrato',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor del Contrato'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='celular_1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular Principal'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='celular_2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular Secundario'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion_1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección Principal'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion_2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección Secundaria'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='documento',
            field=models.CharField(max_length=30, verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Prospecto', 'Prospecto'), ('Suspendido', 'Suspendido')], default='Activo', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre_completo',
            field=models.CharField(max_length=150, verbose_name='Nombre Completo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='referencia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia Personal/Comercial'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('NIT', 'NIT'), ('CE', 'Cédula de Extranjería'), ('PAS', 'Pasaporte'), ('OTRO', 'Otro')], default='CC', max_length=10, verbose_name='Tipo de Documento'),
        ),
    ]
