# Generated by Django 5.2.1 on 2025-05-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_comprobante_ruta_almacenamiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcarga',
            name='fecha_carga',
            field=models.DateTimeField(),
        ),
    ]
