# Generated by Django 5.2.1 on 2025-05-27 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_solicitudcarga_fecha_carga'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprobante',
            name='id_solicitud',
        ),
        migrations.RemoveField(
            model_name='huellacomprobante',
            name='comprobante',
        ),
        migrations.RemoveField(
            model_name='huellacomprobante',
            name='usuario',
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cesion', models.DateField(blank=True, null=True)),
                ('fecha_act', models.DateField(blank=True, null=True)),
                ('documento', models.CharField(max_length=30, unique=True)),
                ('referencia', models.CharField(blank=True, max_length=50, null=True)),
                ('cc', models.CharField(blank=True, max_length=30, null=True)),
                ('nombre_completo', models.CharField(max_length=150)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('dias_mora_originador', models.IntegerField(default=0)),
                ('dias_mora_caso_sas', models.IntegerField(default=0)),
                ('total_dias_mora', models.IntegerField(default=0)),
                ('anios_mora', models.IntegerField(default=0)),
                ('principal', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('deuda_principal_k', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('intereses', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('tecnologia', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('seguro', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('otros_cargos', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('total_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('dcto_pago_contado_50', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('dcto_pago_contado_70_max_30', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('deuda_total', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('telefono_celular', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('celular_1', models.CharField(blank=True, max_length=20, null=True)),
                ('celular_2', models.CharField(blank=True, max_length=20, null=True)),
                ('celular_3', models.CharField(blank=True, max_length=20, null=True)),
                ('celular_4', models.CharField(blank=True, max_length=20, null=True)),
                ('celular_5', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion_1', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion_2', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion_3', models.CharField(blank=True, max_length=255, null=True)),
                ('email_1', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_2', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_3', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono_1', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono_2', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono_3', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='Activo', max_length=20)),
                ('agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='core.empleado')),
            ],
            options={
                'db_table': 'clientes',
                'unique_together': {('documento', 'referencia')},
            },
        ),
        migrations.DeleteModel(
            name='SolicitudCarga',
        ),
        migrations.DeleteModel(
            name='Comprobante',
        ),
        migrations.DeleteModel(
            name='HuellaComprobante',
        ),
    ]
