# Generated by Django 5.2.1 on 2025-05-28 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_cliente_options_remove_cliente_fecha_contrato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='celular_1',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='deuda_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='principal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('CC', 'CC'), ('CE', 'CE'), ('TI', 'TI'), ('NIT', 'NIT'), ('PAS', 'PAS')], max_length=30, null=True),
        ),
    ]
