# Generated by Django 5.2.1 on 2025-05-28 16:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_cliente_celular_1_alter_cliente_deuda_total_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_gestion', models.DateTimeField(default=django.utils.timezone.now)),
                ('canal_contacto', models.CharField(choices=[('telefono', 'Teléfono'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('sms', 'SMS')], max_length=50)),
                ('estado_contacto', models.CharField(choices=[('contactado', 'Contactado'), ('no_contactado', 'No Contactado'), ('numero_errado', 'Número Errado')], max_length=50)),
                ('tipo_gestion_n1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Gestión (Nivel 1)')),
                ('tipo_gestion_n2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Gestión (Nivel 2)')),
                ('tipo_gestion_n3', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Gestión (Nivel 3)')),
                ('acuerdo_pago_realizado', models.BooleanField(default=False, verbose_name='¿Se realizó acuerdo de pago?')),
                ('fecha_acuerdo', models.DateField(blank=True, null=True, verbose_name='Fecha de Acuerdo')),
                ('monto_acuerdo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto del Acuerdo')),
                ('observaciones_acuerdo', models.TextField(blank=True, null=True, verbose_name='Observaciones del Acuerdo')),
                ('seguimiento_requerido', models.BooleanField(default=False, verbose_name='¿Requiere seguimiento?')),
                ('fecha_proximo_seguimiento', models.DateField(blank=True, null=True, verbose_name='Fecha Próximo Seguimiento')),
                ('observaciones_generales', models.TextField(blank=True, null=True, verbose_name='Observaciones Generales de la Gestión')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestiones', to='core.cliente')),
                ('usuario_gestion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gestiones_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gestión',
                'verbose_name_plural': 'Gestiones',
                'ordering': ['-fecha_hora_gestion'],
            },
        ),
    ]
