# Generated by Django 5.2.1 on 2025-05-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_gestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestion',
            name='hora_proximo_seguimiento',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Próximo Seguimiento'),
        ),
    ]
