# Generated by Django 5.2.1 on 2025-05-30 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_gestion_hora_proximo_seguimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestion',
            name='comprobante_pago',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes_pago/', verbose_name='Comprobante de Pago'),
        ),
        migrations.AddField(
            model_name='gestion',
            name='fecha_pago_efectivo',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Pago Efectivo'),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='canal_contacto',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('telefono_in', 'Teléfono IN'), ('telefono_out', 'Teléfono OUT'), ('email', 'Email'), ('sms', 'SMS')], max_length=50),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='estado_contacto',
            field=models.CharField(choices=[('contacto_efectivo', 'Contacto Efectivo'), ('contacto_no_efectivo', 'Contacto No Efectivo'), ('contacto_fallido', 'Contacto Fallido')], max_length=50),
        ),
    ]
