# Generated by Django 5.2.1 on 2025-05-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_gestion_comprobante_pago_gestion_fecha_pago_efectivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestion',
            name='seguimiento_completado',
            field=models.BooleanField(default=False, verbose_name='Seguimiento completado'),
        ),
    ]
