# Generated by Django 5.2.1 on 2025-06-04 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_gestion_seguimiento_completado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gestion',
            name='tipo_gestion_n2',
        ),
        migrations.RemoveField(
            model_name='gestion',
            name='tipo_gestion_n3',
        ),
    ]
