# Generated by Django 5.2.1 on 2025-06-05 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_gestion_tipo_gestion_n2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcuerdoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_acuerdo', models.DateField(verbose_name='Fecha de creación del acuerdo')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto total del acuerdo')),
                ('numero_cuotas', models.PositiveIntegerField(default=1, verbose_name='Número de cuotas')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_curso', 'En curso'), ('completado', 'Completado'), ('incumplido', 'Incumplido'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado del acuerdo')),
                ('tipo_acuerdo', models.CharField(choices=[('pago_total', 'Pago total'), ('pago_parcial', 'Pago parcial')], default='pago_total', max_length=20, verbose_name='Tipo de acuerdo')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acuerdos_pago', to='core.cliente')),
                ('gestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acuerdos', to='core.gestion')),
                ('usuario_creacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acuerdos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acuerdo de pago',
                'verbose_name_plural': 'Acuerdos de pago',
                'ordering': ['-fecha_acuerdo'],
            },
        ),
        migrations.CreateModel(
            name='CuotaAcuerdo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuota', models.PositiveIntegerField(verbose_name='Número de cuota')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto de la cuota')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de vencimiento')),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='Fecha de pago efectivo')),
                ('comprobante_pago', models.FileField(blank=True, null=True, upload_to='comprobantes_cuotas/', verbose_name='Comprobante de pago')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('vencida', 'Vencida')], default='pendiente', max_length=20, verbose_name='Estado de la cuota')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('acuerdo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='core.acuerdopago')),
            ],
            options={
                'verbose_name': 'Cuota de acuerdo',
                'verbose_name_plural': 'Cuotas de acuerdos',
                'ordering': ['acuerdo', 'numero_cuota'],
                'unique_together': {('acuerdo', 'numero_cuota')},
            },
        ),
    ]
