# Generated by Django 5.2.1 on 2025-06-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_acuerdopago_cuotaacuerdo'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestion',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
    ]
