# Generated by Django 5.2.1 on 2025-07-16 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_create_loginuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.AddField(
            model_name='empleado',
            name='campana',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_finalizacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='motivo_finalizacion',
            field=models.CharField(blank=True, choices=[('retiro_voluntario', 'Retiro Voluntario'), ('periodo_prueba', 'No Supera Período de Prueba'), ('despido_justo_causa', 'Despido Con Justo Causa'), ('terminacion_contrato', 'Terminación del Contrato'), ('finaliza_aprendiz', 'Finaliza Periodo de Aprendiz')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='supervisor',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='documento',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='email_empleado',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='foto_empleado',
            field=models.ImageField(blank=True, null=True, upload_to='empleados/fotos/'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='profesion_empleado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='salario_empleado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='sexo_empleado',
            field=models.IntegerField(blank=True, choices=[(1, 'Masculino'), (2, 'Femenino')], null=True),
        ),
        migrations.AlterModelTable(
            name='empleado',
            table='empleados',
        ),
        migrations.CreateModel(
            name='UsuariosPlataformas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_greta', models.CharField(blank=True, max_length=50, null=True, verbose_name='User Greta')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plataformas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Usuario Plataformas',
                'verbose_name_plural': 'Usuarios Plataformas',
                'ordering': ['usuario__username'],
            },
        ),
    ]
