# Generated by Django 5.2.1 on 2025-07-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_empleado_options_empleado_campana_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campana',
            name='modulo',
            field=models.CharField(choices=[('core', 'Core'), ('telefonica', 'Telefónica'), ('calidad', 'Calidad')], default='core', max_length=50, verbose_name='Módulo'),
        ),
    ]
