# Generated by Django 5.2.1 on 2025-08-04 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_campana_modulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campana',
            name='modulo',
            field=models.CharField(choices=[('core', 'Core'), ('telefonica', 'Telefónica'), ('tarjeta_plata', 'Tarjeta Plata'), ('calidad', 'Calidad')], default='core', max_length=50, verbose_name='Módulo'),
        ),
    ]
