# Generated by Django 5.2.1 on 2025-08-04 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_campana_modulo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAccesoIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Dirección IP')),
                ('tipo_acceso', models.CharField(choices=[('login_exitoso', 'Login Exitoso'), ('login_fallido', 'Login Fallido'), ('ip_bloqueada', 'IP Bloqueada'), ('acceso_permitido', 'Acceso Permitido')], max_length=20, verbose_name='Tipo de acceso')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('pais', models.CharField(blank=True, max_length=100, null=True, verbose_name='País')),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad')),
                ('isp', models.CharField(blank=True, max_length=200, null=True, verbose_name='ISP')),
                ('es_vpn', models.BooleanField(default=False, verbose_name='Es VPN')),
                ('es_proxy', models.BooleanField(default=False, verbose_name='Es Proxy')),
                ('puntuacion_riesgo', models.IntegerField(default=0, verbose_name='Puntuación de riesgo')),
                ('fecha_acceso', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de acceso')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_acceso_ip', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de Acceso IP',
                'verbose_name_plural': 'Registros de Acceso IP',
                'ordering': ['-fecha_acceso'],
            },
        ),
        migrations.CreateModel(
            name='IPPermitida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Dirección IP')),
                ('descripcion', models.CharField(help_text='Descripción de la IP (ej: Oficina principal, Casa del gerente, etc.)', max_length=200, verbose_name='Descripción')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True, verbose_name='Último acceso')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ips_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que creó')),
            ],
            options={
                'verbose_name': 'IP Permitida',
                'verbose_name_plural': 'IPs Permitidas',
                'ordering': ['-fecha_creacion'],
                'unique_together': {('ip_address',)},
            },
        ),
    ]
