# Generated by Django 5.2.1 on 2025-07-16 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefonica', '0002_alter_ventaportabilidad_numero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamiento',
            name='Estado_agendamiento',
            field=models.CharField(choices=[('agendado', 'Agendado'), ('venta', 'Venta'), ('no_venta', 'No Venta')], default='agendado', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='ventaportabilidad',
            name='estado_logistica',
            field=models.CharField(choices=[('pendiente_seguimiento', 'Pendiente de Seguimiento'), ('en_transito', 'En Transito'), ('entregado', 'Entregado'), ('rechazado', 'Rechazado')], default='pendiente_seguimiento', max_length=21, verbose_name='Estado Logística'),
        ),
        migrations.AlterField(
            model_name='ventaportabilidad',
            name='estado_venta',
            field=models.CharField(choices=[('pendiente_revision', 'Pendiente de Revisión'), ('escalamiento', 'Escalamiento'), ('cliente_confirma', 'Cliente Confirma'), ('cliente_no_confirma', 'Cliente No Confirma'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('escalamiento_no_solucionado', 'No Solucionado'), ('venta_con_escalamiento', 'Venta con Escalamiento')], default='pendiente_revision', max_length=30, verbose_name='Estado Venta'),
        ),
    ]
