# Generated by Django 5.2.1 on 2025-06-28 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=20, verbose_name='Documento')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('departamento', models.CharField(max_length=100, verbose_name='Departamento')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('barrio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Barrio')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=30, null=True, verbose_name='Número')),
                ('nip', models.CharField(blank=True, max_length=20, null=True, verbose_name='NIP')),
                ('tipo_cliente', models.CharField(choices=[('nuevo', 'Nuevo'), ('existente', 'Existente')], max_length=20, verbose_name='Tipo de Cliente')),
                ('plan_adquiere', models.CharField(max_length=100, verbose_name='Plan Adquirido')),
                ('segmento', models.CharField(choices=[('movil', 'Móvil'), ('hogar', 'Hogar')], max_length=20, verbose_name='Segmento')),
                ('numero_contacto', models.CharField(max_length=20, verbose_name='Número de Contacto')),
                ('imei', models.CharField(blank=True, max_length=30, null=True, verbose_name='IMEI')),
                ('fvc', models.CharField(blank=True, max_length=30, null=True, verbose_name='FVC')),
                ('fecha_entrega', models.DateField(blank=True, null=True, verbose_name='Fecha de Entrega')),
                ('fecha_expedicion', models.DateField(blank=True, null=True, verbose_name='Fecha de Expedición')),
                ('origen', models.CharField(blank=True, max_length=100, null=True, verbose_name='Origen')),
                ('numero_grabacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Grabación')),
                ('selector', models.CharField(blank=True, max_length=100, null=True, verbose_name='Selector')),
                ('orden', models.CharField(blank=True, max_length=100, null=True, verbose_name='Orden')),
                ('confronta', models.FileField(blank=True, null=True, upload_to='confrontas/', verbose_name='Confronta')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('revisados', models.BooleanField(default=False, verbose_name='Revisados')),
                ('estado_revisado', models.CharField(choices=[('pendiente_revision', 'Pendiente de Revisión'), ('devuelta', 'Devuelta para Corrección'), ('aprobada', 'Aprobada'), ('digitada', 'Digitada'), ('rechazada', 'Rechazada'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente_revision', max_length=20, verbose_name='Estado Revisado')),
                ('observacion_2', models.TextField(blank=True, null=True, verbose_name='Observación 2')),
                ('hora', models.TimeField(blank=True, null=True, verbose_name='Hora')),
                ('dia', models.DateField(blank=True, null=True, verbose_name='Día')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Agente')),
                ('backoffice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_revisadas', to=settings.AUTH_USER_MODEL, verbose_name='Backoffice')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='telefonica.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='GestionBackoffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_gestion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Gestión')),
                ('estado', models.CharField(choices=[('pendiente_revision', 'Pendiente de Revisión'), ('devuelta', 'Devuelta para Corrección'), ('aprobada', 'Aprobada'), ('digitada', 'Digitada'), ('rechazada', 'Rechazada'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], max_length=20, verbose_name='Estado')),
                ('comentario', models.TextField(verbose_name='Comentario')),
                ('motivo_devolucion', models.TextField(blank=True, null=True, verbose_name='Motivo de devolución')),
                ('campos_corregir', models.TextField(blank=True, null=True, verbose_name='Campos a corregir')),
                ('backoffice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validaciones', to=settings.AUTH_USER_MODEL, verbose_name='Backoffice')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestiones_backoffice', to='telefonica.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Gestión de Backoffice',
                'verbose_name_plural': 'Gestiones de Backoffice',
                'ordering': ['-fecha_gestion'],
            },
        ),
        migrations.CreateModel(
            name='GestionAsesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_gestion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Gestión')),
                ('estado', models.CharField(choices=[('pendiente_revision', 'Pendiente de Revisión'), ('devuelta', 'Devuelta para Corrección'), ('aprobada', 'Aprobada'), ('digitada', 'Digitada'), ('rechazada', 'Rechazada'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], max_length=20, verbose_name='Estado')),
                ('comentario', models.TextField(verbose_name='Comentario')),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestiones', to=settings.AUTH_USER_MODEL, verbose_name='Agente')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestiones_asesor', to='telefonica.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Gestión de Asesor',
                'verbose_name_plural': 'Gestiones de Asesores',
                'ordering': ['-fecha_gestion'],
            },
        ),
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Cálculo')),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('calculada', 'Calculada'), ('pagada', 'Pagada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comisiones', to=settings.AUTH_USER_MODEL, verbose_name='Agente')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comisiones', to='telefonica.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Comisión',
                'verbose_name_plural': 'Comisiones',
                'ordering': ['-fecha_calculo'],
            },
        ),
    ]
