# Generated by Django 5.2.1 on 2025-07-14 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefonica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventaportabilidad',
            name='numero',
            field=models.CharField(verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='ventaprepos',
            name='numero',
            field=models.CharField(verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='ventaupgrade',
            name='numero',
            field=models.CharField(verbose_name='Número'),
        ),
    ]
