# Generated by Django 5.2.1 on 2025-07-16 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefonica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planes_portabilidad',
            name='tipo_plan',
            field=models.CharField(choices=[('portabilidad', 'Portabilidad'), ('prepos', 'PrePos'), ('upgrade', 'Upgrade')], default='portabilidad', max_length=20, verbose_name='Tipo de Plan'),
        ),
        migrations.AlterField(
            model_name='planes_portabilidad',
            name='codigo',
            field=models.CharField(max_length=50, unique=True, verbose_name='Código'),
        ),
    ]
