# Generated by Django 5.2.1 on 2025-01-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefonica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaportabilidad',
            name='confronta_minio_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL MinIO del Confronta'),
        ),
        migrations.AddField(
            model_name='ventaportabilidad',
            name='confronta_minio_object_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Nombre del Objeto en MinIO'),
        ),
        migrations.AddField(
            model_name='ventaportabilidad',
            name='confronta_subido_a_minio',
            field=models.BooleanField(default=False, verbose_name='Subido a MinIO'),
        ),
        migrations.AddField(
            model_name='ventaportabilidad',
            name='confronta_fecha_subida_minio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Subida a MinIO'),
        ),
    ]