# Generated by Django 5.2.1 on 2025-06-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefonica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'CC'), ('CE', 'CE'), ('NIT', 'NIT'), ('PP', 'Pasaporte')], default='CC', max_length=10, verbose_name='Tipo de Documento'),
        ),
    ]
