# Generated by Django 5.2.1 on 2025-07-17 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefonica', '0002_planes_portabilidad_tipo_plan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamiento',
            name='Estado_agendamiento',
            field=models.CharField(choices=[('agendado', 'Agendado'), ('venta', 'Venta'), ('volver_llamar', 'Volver a LLamar'), ('no_acepta_oferta', 'Cliente No Acepta Oferta'), ('no_contactado', 'Cliente No Contactado')], default='agendado', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='ventaprepos',
            name='base_origen',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Base Origen'),
        ),
        migrations.AlterField(
            model_name='ventaprepos',
            name='usuario_greta',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuario Greta'),
        ),
        migrations.CreateModel(
            name='GestionAgendamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(verbose_name='Comentario')),
                ('estado_anterior', models.CharField(choices=[('agendado', 'Agendado'), ('venta', 'Venta'), ('volver_llamar', 'Volver a LLamar'), ('no_acepta_oferta', 'Cliente No Acepta Oferta'), ('no_contactado', 'Cliente No Contactado')], max_length=20, verbose_name='Estado Anterior')),
                ('estado_nuevo', models.CharField(choices=[('agendado', 'Agendado'), ('venta', 'Venta'), ('volver_llamar', 'Volver a LLamar'), ('no_acepta_oferta', 'Cliente No Acepta Oferta'), ('no_contactado', 'Cliente No Contactado')], max_length=20, verbose_name='Estado Nuevo')),
                ('fecha_gestion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Gestión')),
                ('agendamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestiones', to='telefonica.agendamiento', verbose_name='Agendamiento')),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestiones_agendamiento', to=settings.AUTH_USER_MODEL, verbose_name='Agente')),
            ],
            options={
                'verbose_name': 'Gestión de Agendamiento',
                'verbose_name_plural': 'Gestiones de Agendamientos',
                'ordering': ['-fecha_gestion'],
            },
        ),
    ]
