# Generated by Django 5.2.1 on 2025-07-13 00:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefonica', '0002_cliente_tipo_documento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Primero eliminamos las tablas antiguas para evitar problemas de clave foránea
        migrations.RunSQL(
            """DROP TABLE IF EXISTS telefonica_comision CASCADE;
               DROP TABLE IF EXISTS telefonica_gestionasesor CASCADE;
               DROP TABLE IF EXISTS telefonica_gestionbackoffice CASCADE;
               DROP TABLE IF EXISTS telefonica_venta CASCADE;
               DROP TABLE IF EXISTS telefonica_cliente CASCADE;
            """,
            reverse_sql=migrations.RunSQL.noop
        ),
        
        # Crear modelo Planes_portabilidad
        migrations.CreateModel(
            name='Planes_portabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Código')),
                ('nombre_plan', models.CharField(max_length=150, verbose_name='Nombre del Plan')),
                ('caracteristicas', models.TextField(verbose_name='Características')),
                ('CFM', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cargo Fijo Mensual')),
                ('CFM_sin_iva', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cargo Fijo Mensual sin IVA')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'ordering': ['nombre_plan'],
            },
        ),
        
        # Crear modelo VentaPortabilidad
        migrations.CreateModel(
            name='VentaPortabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='Número')),
                ('tipo_cliente', models.CharField(choices=[('dentro_base', 'Dentro de la Base'), ('fuera_base', 'Fuera de la Base')], max_length=20, verbose_name='Tipo de Cliente')),
                ('tipo_documento', models.CharField(choices=[('CC', 'CC'), ('CE', 'CE'), ('NIT', 'NIT'), ('PP', 'Pasaporte')], default='CC', max_length=10, verbose_name='Tipo de Documento')),
                ('documento', models.CharField(max_length=15, verbose_name='Documento')),
                ('fecha_expedicion', models.DateField(verbose_name='Fecha de Expedición')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('telefono_legalizacion', models.CharField(max_length=10, verbose_name='Teléfono Legalización')),
                ('numero_a_portar', models.CharField(max_length=10, verbose_name='Número a Portar')),
                ('nip', models.IntegerField(verbose_name='NIP')),
                ('fecha_entrega', models.DateField(verbose_name='Fecha de Entrega')),
                ('fecha_ventana_cambio', models.DateField(verbose_name='Fecha de Ventana de Cambio')),
                ('numero_orden', models.IntegerField(verbose_name='Número de Orden')),
                ('base_origen', models.CharField(max_length=100, verbose_name='Base Origen')),
                ('usuario_greta', models.CharField(max_length=100, verbose_name='Usuario Greta')),
                ('confronta', models.FileField(blank=True, null=True, upload_to='confrontas/', verbose_name='Confronta')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('estado_venta', models.CharField(choices=[('pendiente_revision', 'Pendiente de Revisión'), ('escalamiento', 'Escalamiento'), ('cliente_confirma', 'Cliente Confirma'), ('cliente_no_confirma', 'Cliente No Confirma'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('escalamiento_no_solucionado', 'No Solucionado'), ('venta_con_escalamiento', 'Venta con Escalamiento')], default='pendiente_revision', max_length=30, verbose_name='Estado')),
                ('estado_logistica', models.CharField(choices=[('en_transito', 'En Transito'), ('entregado', 'Entregado'), ('rechazado', 'Rechazado')], default='pendiente_revision', max_length=20, verbose_name='Estado Logística')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_portabilidad_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Agente')),
                ('backoffice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_portabilidad_revisadas', to=settings.AUTH_USER_MODEL, verbose_name='Backoffice')),
                ('plan_adquiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_portabilidad', to='telefonica.planes_portabilidad', verbose_name='Plan Adquirido')),
            ],
            options={
                'verbose_name': 'Venta Portabilidad',
                'verbose_name_plural': 'Ventas Portabilidad',
                'ordering': ['-fecha_creacion'],
            },
        ),
        
        # Crear modelo VentaPrePos
        migrations.CreateModel(
            name='VentaPrePos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='Número')),
                ('tipo_cliente', models.CharField(choices=[('dentro_base', 'Dentro de la Base'), ('fuera_base', 'Fuera de la Base')], max_length=20, verbose_name='Tipo de Cliente')),
                ('tipo_documento', models.CharField(choices=[('CC', 'CC'), ('CE', 'CE'), ('NIT', 'NIT'), ('PP', 'Pasaporte')], default='CC', max_length=10, verbose_name='Tipo de Documento')),
                ('documento', models.CharField(max_length=15, verbose_name='Documento')),
                ('fecha_expedicion', models.DateField(verbose_name='Fecha de Expedición')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('telefono_legalizacion', models.CharField(max_length=10, verbose_name='Teléfono Legalización')),
                ('numero_orden', models.IntegerField(verbose_name='Número de Orden')),
                ('base_origen', models.CharField(max_length=100, verbose_name='Base Origen')),
                ('usuario_greta', models.CharField(max_length=100, verbose_name='Usuario Greta')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_prepos_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Agente')),
                ('plan_adquiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_prepos', to='telefonica.planes_portabilidad', verbose_name='Plan Adquirido')),
            ],
            options={
                'verbose_name': 'Venta PrePos',
                'verbose_name_plural': 'Ventas PrePos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        
        # Crear modelo VentaUpgrade
        migrations.CreateModel(
            name='VentaUpgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='Número')),
                ('tipo_cliente', models.CharField(choices=[('dentro_base', 'Dentro de la Base'), ('fuera_base', 'Fuera de la Base')], max_length=20, verbose_name='Tipo de Cliente')),
                ('tipo_documento', models.CharField(choices=[('CC', 'CC'), ('CE', 'CE'), ('NIT', 'NIT'), ('PP', 'Pasaporte')], default='CC', max_length=10, verbose_name='Tipo de Documento')),
                ('documento', models.CharField(max_length=15, verbose_name='Documento')),
                ('fecha_expedicion', models.DateField(verbose_name='Fecha de Expedición')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('telefono_legalizacion', models.CharField(max_length=10, verbose_name='Teléfono Legalización')),
                ('codigo_verificacion', models.CharField(max_length=6, verbose_name='Código de Verificación')),
                ('numero_orden', models.IntegerField(verbose_name='Número de Orden')),
                ('base_origen', models.CharField(max_length=100, verbose_name='Base Origen')),
                ('usuario_greta', models.CharField(max_length=100, verbose_name='Usuario Greta')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_upgrade_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Agente')),
                ('plan_adquiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_upgrade', to='telefonica.planes_portabilidad', verbose_name='Plan Adquirido')),
            ],
            options={
                'verbose_name': 'Venta Upgrade',
                'verbose_name_plural': 'Ventas Upgrade',
                'ordering': ['-fecha_creacion'],
            },
        ),
        
        # Crear modelo agendamiento
        migrations.CreateModel(
            name='agendamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estado_agendamiento', models.CharField(choices=[('agendado', 'Agendado'), ('venta', 'Venta'), ('no_venta', 'No Venta')], default='pendiente_revision', max_length=20, verbose_name='Estado')),
                ('nombre_cliente', models.CharField(max_length=100, verbose_name='Nombre del Cliente')),
                ('telefono_contacto', models.CharField(max_length=15, verbose_name='Teléfono de Contacto')),
                ('fecha_volver_a_llamar', models.DateField(verbose_name='Fecha de Volver a Llamar')),
                ('hora_volver_a_llamar', models.TimeField(verbose_name='Hora de Volver a Llamar')),
                ('observaciones', models.TextField(verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamientos', to=settings.AUTH_USER_MODEL, verbose_name='Agente')),
            ],
            options={
                'verbose_name': 'Agendamiento',
                'verbose_name_plural': 'Agendamientos',
                'ordering': ['-fecha_volver_a_llamar'],
            },
        ),
        
        # Crear modelo GestionAsesor
        migrations.CreateModel(
            name='GestionAsesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(verbose_name='Comentario')),
                ('fecha_gestion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Gestión')),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestiones', to=settings.AUTH_USER_MODEL, verbose_name='Agente')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestiones_asesor', to='telefonica.ventaportabilidad', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Gestión Asesor',
                'verbose_name_plural': 'Gestiones Asesores',
                'ordering': ['-fecha_gestion'],
            },
        ),
        
        # Crear modelo GestionBackoffice
        migrations.CreateModel(
            name='GestionBackoffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(verbose_name='Comentario')),
                ('fecha_gestion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Gestión')),
                ('backoffice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validaciones', to=settings.AUTH_USER_MODEL, verbose_name='Backoffice')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestiones_backoffice', to='telefonica.ventaportabilidad', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Gestión Backoffice',
                'verbose_name_plural': 'Gestiones Backoffice',
                'ordering': ['-fecha_gestion'],
            },
        ),
        
        # Crear modelo Escalamiento
        migrations.CreateModel(
            name='Escalamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_escalamiento', models.CharField(choices=[('documentacion', 'Documentación'), ('sistema', 'Sistema'), ('otro', 'Otro')], max_length=20, verbose_name='Tipo de Escalamiento')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fecha_escalamiento', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Escalamiento')),
                ('fecha_solucion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Solución')),
                ('solucionado', models.BooleanField(default=False, verbose_name='Solucionado')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalamientos', to='telefonica.ventaportabilidad', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Escalamiento',
                'verbose_name_plural': 'Escalamientos',
                'ordering': ['-fecha_escalamiento'],
            },
        ),
        
        # Crear modelo Comision
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monto')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comisiones', to=settings.AUTH_USER_MODEL, verbose_name='Agente')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comisiones', to='telefonica.ventaportabilidad', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Comisión',
                'verbose_name_plural': 'Comisiones',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
