# Generated by Django 5.2.1 on 2025-07-16 02:07

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('telefonica', '0003_alter_agendamiento_estado_agendamiento_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            """
            DO $$
            BEGIN
                IF NOT EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'telefonica_ventaportabilidad') THEN
                    CREATE TABLE telefonica_ventaportabilidad (
                        id bigserial NOT NULL PRIMARY KEY,
                        numero varchar(255) NOT NULL,
                        tipo_cliente varchar(20) NOT NULL,
                        tipo_documento varchar(10) NOT NULL,
                        documento varchar(15) NOT NULL,
                        fecha_expedicion date NOT NULL,
                        nombres varchar(100) NOT NULL,
                        apellidos varchar(100) NOT NULL,
                        telefono_legalizacion varchar(10) NOT NULL,
                        numero_a_portar varchar(10) NOT NULL,
                        nip integer NOT NULL,
                        fecha_entrega date NOT NULL,
                        fecha_ventana_cambio date NOT NULL,
                        numero_orden integer NOT NULL,
                        base_origen varchar(100) NOT NULL,
                        usuario_greta varchar(100) NOT NULL,
                        observacion text,
                        estado_venta varchar(30) NOT NULL,
                        estado_logistica varchar(21) NOT NULL,
                        fecha_creacion timestamp with time zone NOT NULL,
                        fecha_actualizacion timestamp with time zone NOT NULL,
                        agente_id integer REFERENCES auth_user(id) ON DELETE SET NULL,
                        backoffice_id integer REFERENCES auth_user(id) ON DELETE SET NULL,
                        plan_adquiere_id integer NOT NULL REFERENCES telefonica_planes_portabilidad(id) ON DELETE RESTRICT
                    );
                END IF;
                
                IF NOT EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'telefonica_ventaprepos') THEN
                    CREATE TABLE telefonica_ventaprepos (
                        id bigserial NOT NULL PRIMARY KEY,
                        numero varchar(255) NOT NULL,
                        tipo_cliente varchar(20) NOT NULL,
                        tipo_documento varchar(10) NOT NULL,
                        documento varchar(15) NOT NULL,
                        fecha_expedicion date NOT NULL,
                        nombres varchar(100) NOT NULL,
                        apellidos varchar(100) NOT NULL,
                        telefono_legalizacion varchar(10) NOT NULL,
                        numero_orden integer NOT NULL,
                        base_origen varchar(100) NOT NULL,
                        usuario_greta varchar(100) NOT NULL,
                        observacion text,
                        fecha_creacion timestamp with time zone NOT NULL,
                        fecha_actualizacion timestamp with time zone NOT NULL,
                        agente_id integer REFERENCES auth_user(id) ON DELETE SET NULL,
                        plan_adquiere_id integer NOT NULL REFERENCES telefonica_planes_portabilidad(id) ON DELETE RESTRICT
                    );
                END IF;
                
                IF NOT EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'telefonica_ventaupgrade') THEN
                    CREATE TABLE telefonica_ventaupgrade (
                        id bigserial NOT NULL PRIMARY KEY,
                        numero varchar(255) NOT NULL,
                        tipo_cliente varchar(20) NOT NULL,
                        tipo_documento varchar(10) NOT NULL,
                        documento varchar(15) NOT NULL,
                        fecha_expedicion date NOT NULL,
                        nombres varchar(100) NOT NULL,
                        apellidos varchar(100) NOT NULL,
                        telefono_legalizacion varchar(10) NOT NULL,
                        codigo_verificacion varchar(6) NOT NULL,
                        numero_orden integer NOT NULL,
                        base_origen varchar(100) NOT NULL,
                        usuario_greta varchar(100) NOT NULL,
                        observacion text,
                        fecha_creacion timestamp with time zone NOT NULL,
                        fecha_actualizacion timestamp with time zone NOT NULL,
                        agente_id integer REFERENCES auth_user(id) ON DELETE SET NULL,
                        plan_adquiere_id integer NOT NULL REFERENCES telefonica_planes_portabilidad(id) ON DELETE RESTRICT
                    );
                END IF;
            END
            $$;
            """,
            """
            -- No se necesita un rollback específico ya que las tablas se crean solo si no existen
            """
        )
    ]
