# Generated by Django 5.2.1 on 2025-07-18 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefonica', '0003_alter_agendamiento_estado_agendamiento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientesPrePos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=20, unique=True, verbose_name='Teléfono')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
            ],
            options={
                'verbose_name': 'Cliente PrePos',
                'verbose_name_plural': 'Clientes PrePos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ClientesUpgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_base', models.CharField(max_length=100, unique=True, verbose_name='ID Base')),
                ('nro_registro', models.CharField(max_length=50, verbose_name='Número de Registro')),
                ('campana', models.CharField(max_length=200, verbose_name='Campaña')),
                ('grupo_campana', models.CharField(max_length=200, verbose_name='Grupo Campaña')),
                ('estrategia', models.CharField(max_length=100, verbose_name='Estrategia')),
                ('nombre_cliente', models.CharField(max_length=200, verbose_name='Nombre Cliente')),
                ('tipo_documento', models.CharField(choices=[('CC', 'CC'), ('CE', 'CE'), ('NIT', 'NIT'), ('PP', 'Pasaporte')], max_length=10, verbose_name='Tipo de Documento')),
                ('documento', models.CharField(max_length=15, verbose_name='Documento')),
                ('direccion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección')),
                ('estrato', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Estrato')),
                ('barrio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Barrio')),
                ('departamento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Departamento')),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad')),
                ('producto', models.CharField(max_length=50, verbose_name='Producto')),
                ('puertos_disponibles', models.CharField(blank=True, max_length=10, null=True, verbose_name='Puertos Disponibles')),
                ('promedio_fact', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Promedio Facturación')),
                ('mx_tenencia_cuenta', models.CharField(blank=True, max_length=50, null=True, verbose_name='Máx Tenencia Cuenta')),
                ('tel_contacto_1', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono Contacto 1')),
                ('tel_contacto_2', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono Contacto 2')),
                ('tel_contacto_3', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono Contacto 3')),
                ('celular_contacto', models.CharField(blank=True, max_length=15, null=True, verbose_name='Celular Contacto')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Cliente Upgrade',
                'verbose_name_plural': 'Clientes Upgrade',
                'ordering': ['nombre_cliente'],
            },
        ),
        migrations.RemoveField(
            model_name='ventaportabilidad',
            name='tipo_cliente',
        ),
        migrations.AddField(
            model_name='agendamiento',
            name='tipo_venta',
            field=models.CharField(choices=[('portabilidad', 'Portabilidad'), ('prepos', 'PrePos'), ('upgrade', 'Upgrade')], default='portabilidad', max_length=20, verbose_name='Tipo de Venta'),
        ),
        migrations.AddField(
            model_name='ventaprepos',
            name='estado_venta',
            field=models.CharField(choices=[('enviada', 'Enviada')], default='enviada', max_length=30, verbose_name='Estado Venta'),
        ),
        migrations.AddField(
            model_name='ventaupgrade',
            name='estado_venta',
            field=models.CharField(choices=[('enviada', 'Enviada')], default='enviada', max_length=30, verbose_name='Estado Venta'),
        ),
        migrations.AlterField(
            model_name='ventaprepos',
            name='tipo_cliente',
            field=models.CharField(choices=[('dentro_base', 'Dentro de Base'), ('fuera_base', 'Fuera de Base')], default='fuera_base', max_length=20, verbose_name='Tipo de Cliente'),
        ),
        migrations.AlterField(
            model_name='ventaupgrade',
            name='tipo_cliente',
            field=models.CharField(choices=[('dentro_base', 'Dentro de Base'), ('fuera_base', 'Fuera de Base')], default='fuera_base', max_length=20, verbose_name='Tipo de Cliente'),
        ),
        migrations.AddField(
            model_name='ventaprepos',
            name='cliente_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='telefonica.clientesprepos', verbose_name='Cliente Base'),
        ),
        migrations.AddField(
            model_name='ventaupgrade',
            name='cliente_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_realizadas', to='telefonica.clientesupgrade', verbose_name='Cliente de Base'),
        ),
    ]
