# Generated by Django 5.2.1 on 2025-07-18 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefonica', '0004_clientesprepos_clientesupgrade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientesupgrade',
            name='id_base',
            field=models.CharField(max_length=100, verbose_name='ID Base'),
        ),
        migrations.AlterField(
            model_name='clientesupgrade',
            name='nro_registro',
            field=models.CharField(max_length=50, unique=True, verbose_name='Número de Registro'),
        ),
    ]
