# Generated by Django 5.2.1 on 2025-07-16 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefonica', '0004_auto_20250715_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaprepos',
            name='estado_logistica',
            field=models.CharField(choices=[('pendiente_seguimiento', 'Pendiente de Seguimiento'), ('en_transito', 'En Transito'), ('entregado', 'Entregado'), ('rechazado', 'Rechazado')], default='pendiente_seguimiento', max_length=21, verbose_name='Estado Logística'),
        ),
        migrations.AddField(
            model_name='ventaprepos',
            name='estado_venta',
            field=models.CharField(choices=[('pendiente_revision', 'Pendiente de Revisión'), ('escalamiento', 'Escalamiento'), ('cliente_confirma', 'Cliente Confirma'), ('cliente_no_confirma', 'Cliente No Confirma'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('escalamiento_no_solucionado', 'No Solucionado'), ('venta_con_escalamiento', 'Venta con Escalamiento')], default='pendiente_revision', max_length=30, verbose_name='Estado Venta'),
        ),
        migrations.AddField(
            model_name='ventaupgrade',
            name='estado_logistica',
            field=models.CharField(choices=[('pendiente_seguimiento', 'Pendiente de Seguimiento'), ('en_transito', 'En Transito'), ('entregado', 'Entregado'), ('rechazado', 'Rechazado')], default='pendiente_seguimiento', max_length=21, verbose_name='Estado Logística'),
        ),
        migrations.AddField(
            model_name='ventaupgrade',
            name='estado_venta',
            field=models.CharField(choices=[('pendiente_revision', 'Pendiente de Revisión'), ('escalamiento', 'Escalamiento'), ('cliente_confirma', 'Cliente Confirma'), ('cliente_no_confirma', 'Cliente No Confirma'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('escalamiento_no_solucionado', 'No Solucionado'), ('venta_con_escalamiento', 'Venta con Escalamiento')], default='pendiente_revision', max_length=30, verbose_name='Estado Venta'),
        ),
    ]
