# Generated by Django 5.2.1 on 2025-07-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefonica', '0006_add_nombre_completo_remove_nombres_apellidos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventaportabilidad',
            name='base_origen',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Base Origen'),
        ),
        migrations.AlterField(
            model_name='ventaportabilidad',
            name='usuario_greta',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuario Greta'),
        ),
    ]
