# Generated by Django 5.2.1 on 2025-07-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefonica', '0007_alter_ventaportabilidad_base_origen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventaupgrade',
            name='base_origen',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Base Origen'),
        ),
        migrations.AlterField(
            model_name='ventaupgrade',
            name='usuario_greta',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuario Greta'),
        ),
    ]
