# Generated by Django 5.2.1 on 2025-07-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefonica', '0008_alter_ventaupgrade_base_origen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaportabilidad',
            name='plan_caracteristicas',
            field=models.TextField(blank=True, null=True, verbose_name='Características del Plan'),
        ),
        migrations.AddField(
            model_name='ventaportabilidad',
            name='plan_cfm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='CFM del Plan'),
        ),
        migrations.AddField(
            model_name='ventaportabilidad',
            name='plan_cfm_sin_iva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='CFM sin IVA del Plan'),
        ),
        migrations.AddField(
            model_name='ventaportabilidad',
            name='plan_codigo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código del Plan'),
        ),
        migrations.AddField(
            model_name='ventaportabilidad',
            name='plan_nombre',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre del Plan'),
        ),
        migrations.AddField(
            model_name='ventaprepos',
            name='plan_caracteristicas',
            field=models.TextField(blank=True, null=True, verbose_name='Características del Plan'),
        ),
        migrations.AddField(
            model_name='ventaprepos',
            name='plan_cfm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='CFM del Plan'),
        ),
        migrations.AddField(
            model_name='ventaprepos',
            name='plan_cfm_sin_iva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='CFM sin IVA del Plan'),
        ),
        migrations.AddField(
            model_name='ventaprepos',
            name='plan_codigo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código del Plan'),
        ),
        migrations.AddField(
            model_name='ventaprepos',
            name='plan_nombre',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre del Plan'),
        ),
        migrations.AddField(
            model_name='ventaupgrade',
            name='plan_caracteristicas',
            field=models.TextField(blank=True, null=True, verbose_name='Características del Plan'),
        ),
        migrations.AddField(
            model_name='ventaupgrade',
            name='plan_cfm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='CFM del Plan'),
        ),
        migrations.AddField(
            model_name='ventaupgrade',
            name='plan_cfm_sin_iva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='CFM sin IVA del Plan'),
        ),
        migrations.AddField(
            model_name='ventaupgrade',
            name='plan_codigo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código del Plan'),
        ),
        migrations.AddField(
            model_name='ventaupgrade',
            name='plan_nombre',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre del Plan'),
        ),
    ]
