# Generated by Django 5.2.1 on 2025-07-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefonica', '0009_ventaportabilidad_plan_caracteristicas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventaportabilidad',
            name='nombre_completo',
            field=models.CharField(max_length=200, verbose_name='Nombre Completo'),
        ),
        migrations.AlterField(
            model_name='ventaportabilidad',
            name='numero_orden',
            field=models.CharField(max_length=50, verbose_name='Número de Orden'),
        ),
        migrations.AlterField(
            model_name='ventaprepos',
            name='numero_orden',
            field=models.CharField(max_length=50, verbose_name='Número de Orden'),
        ),
        migrations.AlterField(
            model_name='ventaupgrade',
            name='numero_orden',
            field=models.CharField(max_length=50, verbose_name='Número de Orden'),
        ),
    ]
