# Generated by Django 5.2.1 on 2025-08-11 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telefonica', '0002_add_minio_fields_to_ventaportabilidad'),
        ('telefonica', '0010_alter_ventaportabilidad_nombre_completo_and_more'),
    ]

    operations = [
    ]
