# Generated by Django 5.2.1 on 2025-08-11 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telefonica', '0002_remove_confronta_add_minio_only'),
        ('telefonica', '0011_merge_20250810_2021'),
    ]

    operations = [
    ]
