# Generated by Django 5.2.1 on 2025-09-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telefonica", "0012_merge_20250811_1056"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ventaupgrade",
            name="codigo_verificacion",
        ),
        migrations.AddField(
            model_name="ventaupgrade",
            name="valor_plan_anterior",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=6,
                verbose_name="Valor Plan Anterior",
            ),
        ),
    ]
