# Generated by Django 5.2.1 on 2025-09-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telefonica", "0013_remove_ventaupgrade_codigo_verificacion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ventaupgrade",
            name="valor_plan_anterior",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Valor Plan Anterior",
            ),
        ),
    ]
