# Generated by Django 5.2.1 on 2025-09-08 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telefonica", "0014_alter_ventaupgrade_valor_plan_anterior"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ventaportabilidad",
            name="numero_orden",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Número de Orden"
            ),
        ),
        migrations.AlterField(
            model_name="ventaprepos",
            name="numero_orden",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Número de Orden"
            ),
        ),
        migrations.AlterField(
            model_name="ventaupgrade",
            name="numero_orden",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Número de Orden"
            ),
        ),
    ]
