# Generated by Django 5.2.1 on 2025-10-10 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telefonica", "0016_alter_ventaupgrade_valor_plan_anterior"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="planes_portabilidad",
            name="tipo_plan",
            field=models.CharField(
                choices=[
                    ("portabilidad", "Portabilidad"),
                    ("prepos", "PrePos"),
                    ("upgrade", "Upgrade"),
                    ("Hogar", "Hogar"),
                ],
                default="portabilidad",
                max_length=20,
                verbose_name="Tipo de Plan",
            ),
        ),
        migrations.CreateModel(
            name="VentaHogar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=30, verbose_name="Número")),
                (
                    "tipo_cliente",
                    models.CharField(
                        choices=[
                            ("dentro_base", "Dentro de Base"),
                            ("fuera_base", "Fuera de Base"),
                        ],
                        default="fuera_base",
                        max_length=20,
                        verbose_name="Tipo de Cliente",
                    ),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("CC", "CC"),
                            ("CE", "CE"),
                            ("NIT", "NIT"),
                            ("PP", "Pasaporte"),
                        ],
                        default="CC",
                        max_length=10,
                        verbose_name="Tipo de Documento",
                    ),
                ),
                (
                    "documento",
                    models.CharField(max_length=15, verbose_name="Documento"),
                ),
                (
                    "nombre_completo",
                    models.CharField(max_length=100, verbose_name="Nombre Completo"),
                ),
                (
                    "telefono_legalizacion",
                    models.CharField(
                        max_length=10, verbose_name="Teléfono Legalización"
                    ),
                ),
                (
                    "fecha_instalacion",
                    models.DateField(verbose_name="Fecha de Instalación"),
                ),
                (
                    "numero_orden",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Número de Orden"
                    ),
                ),
                (
                    "base_origen",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Base Origen",
                    ),
                ),
                (
                    "usuario_greta",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Usuario Greta",
                    ),
                ),
                (
                    "observacion",
                    models.TextField(blank=True, null=True, verbose_name="Observación"),
                ),
                (
                    "plan_nombre",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Nombre del Plan",
                    ),
                ),
                (
                    "plan_codigo",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Código del Plan",
                    ),
                ),
                (
                    "plan_caracteristicas",
                    models.TextField(
                        blank=True, null=True, verbose_name="Características del Plan"
                    ),
                ),
                (
                    "plan_cfm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="CFM del Plan",
                    ),
                ),
                (
                    "plan_cfm_sin_iva",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="CFM sin IVA del Plan",
                    ),
                ),
                (
                    "estado_venta",
                    models.CharField(
                        choices=[("enviada", "Enviada")],
                        default="enviada",
                        max_length=30,
                        verbose_name="Estado Venta",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Actualización"
                    ),
                ),
                (
                    "agente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ventas_hogar_realizadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Agente",
                    ),
                ),
                (
                    "cliente_base",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="telefonica.clientesprepos",
                        verbose_name="Cliente Base",
                    ),
                ),
                (
                    "plan_adquiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ventas_hogar",
                        to="telefonica.planes_portabilidad",
                        verbose_name="Plan Adquirido",
                    ),
                ),
            ],
            options={
                "verbose_name": "Venta Hogar",
                "verbose_name_plural": "Ventas Hogar",
                "ordering": ["-fecha_creacion"],
            },
        ),
    ]
