# Generated by Django 4.2.23 on 2025-11-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telefonica", "0017_alter_planes_portabilidad_tipo_plan_ventahogar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ventahogar",
            name="numero",
            field=models.CharField(max_length=30, verbose_name="Número"),
        ),
        migrations.AlterField(
            model_name="ventaportabilidad",
            name="numero",
            field=models.CharField(max_length=30, verbose_name="Número"),
        ),
        migrations.AlterField(
            model_name="ventaprepos",
            name="numero",
            field=models.CharField(max_length=30, verbose_name="Número"),
        ),
        migrations.AlterField(
            model_name="ventaupgrade",
            name="numero",
            field=models.CharField(max_length=30, verbose_name="Número"),
        ),
    ]
