# Generated by Django 5.2.1 on 2025-07-23 19:01

import calidad.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_telefono', models.CharField(help_text='Número de teléfono del cliente', max_length=20, verbose_name='Número de teléfono')),
                ('fecha_llamada', models.DateField(default=django.utils.timezone.now, help_text='Fecha en que se realizó la llamada', verbose_name='Fecha de la llamada')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones generales de la auditoría', null=True, verbose_name='Observaciones')),
                ('sede', models.CharField(choices=[('bogota', 'Bogotá'), ('medellin', 'Medellín')], help_text='Sede donde se realizó la llamada', max_length=20, verbose_name='Sede')),
                ('area', models.CharField(choices=[('entrenamiento', 'Entrenamiento'), ('calidad', 'Calidad'), ('operacion', 'Operación')], help_text='Área a la que pertenece el agente', max_length=20, verbose_name='Área')),
                ('tipo_monitoreo', models.CharField(choices=[('speech', 'Speech Analytics'), ('al_lado', 'Al Lado'), ('grabacion', 'Grabación'), ('remoto', 'Remoto en Línea')], help_text='Tipo de monitoreo realizado', max_length=20, verbose_name='Tipo de monitoreo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('puntaje_total', models.DecimalField(decimal_places=2, default=0.0, help_text='Puntaje final de la auditoría', max_digits=5, verbose_name='Puntaje Total')),
                ('observaciones_tipificacion', models.TextField(blank=True, help_text='Detalles sobre el logueo de la llamada: tipificación, notas, etc.', null=True, verbose_name='Observaciones de Tipificación')),
                ('puntaje_ia', models.CharField(blank=True, help_text='Puntaje total de la evaluación de IA', max_length=10, null=True)),
                ('resumen_ia', models.TextField(blank=True, help_text='Resumen de la evaluación de calidad generado por IA', null=True)),
                ('tipificacion', models.CharField(choices=[('venta', 'Venta'), ('soporte', 'Soporte'), ('reclamo', 'Reclamo'), ('cotizacion', 'Cotización'), ('otro', 'Otro')], default='otro', help_text='Tipo de interacción con el cliente', max_length=20, verbose_name='Tipificación')),
                ('agente', models.ForeignKey(help_text='Agente que está siendo evaluado', on_delete=django.db.models.deletion.PROTECT, related_name='auditorias_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='Agente evaluado')),
                ('evaluador', models.ForeignKey(help_text='Persona que realiza la evaluación', limit_choices_to={'groups__name': 'Calidad'}, on_delete=django.db.models.deletion.PROTECT, related_name='auditorias_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Evaluador')),
            ],
            options={
                'verbose_name': 'Auditoría',
                'verbose_name_plural': 'Auditorías',
                'ordering': ['-fecha_llamada'],
                'permissions': [('puede_ver_auditorias', 'Puede ver auditorías'), ('puede_editar_auditorias', 'Puede editar auditorías'), ('puede_eliminar_auditorias', 'Puede eliminar auditorías')],
            },
        ),
        migrations.CreateModel(
            name='MatrizCalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipologia', models.CharField(choices=[('ECUF', 'ECUF'), ('ECN', 'ECN'), ('ofrecimiento_comercial', 'Ofrecimiento Comercial')], help_text='Tipo de interacción o comunicación', max_length=50, verbose_name='Tipología')),
                ('categoria', models.CharField(help_text='Nombre de la categoría del indicador', max_length=100, verbose_name='Categoría')),
                ('indicador', models.CharField(help_text='Descripción del indicador de calidad', max_length=255, verbose_name='Indicador')),
                ('ponderacion', models.DecimalField(decimal_places=2, help_text='Peso del indicador en la evaluación total (0.01 - 100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(100)], verbose_name='Ponderación (%)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('usuario_creacion', models.ForeignKey(help_text='Usuario que creó el registro', on_delete=django.db.models.deletion.PROTECT, related_name='matrices_inbound_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Creación')),
            ],
            options={
                'verbose_name': 'Matriz de Calidad',
                'verbose_name_plural': 'Matrices de Calidad',
                'ordering': ['categoria', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MatrizCalidadInbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipologia', models.CharField(choices=[('ECUF', 'ECUF'), ('ECN', 'ECN'), ('ofrecimiento_comercial', 'Ofrecimiento Comercial')], help_text='Tipo de interacción o comunicación', max_length=50, verbose_name='Tipología')),
                ('categoria', models.CharField(help_text='Nombre de la categoría del indicador', max_length=100, verbose_name='Categoría')),
                ('indicador', models.CharField(help_text='Descripción del indicador de calidad', max_length=255, verbose_name='Indicador')),
                ('ponderacion', models.DecimalField(decimal_places=2, help_text='Peso del indicador en la evaluación total (0.01 - 100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(100)], verbose_name='Ponderación (%)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('usuario_creacion', models.ForeignKey(help_text='Usuario que creó el registro', on_delete=django.db.models.deletion.PROTECT, related_name='matrices_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Creación')),
            ],
            options={
                'verbose_name': 'Matriz de Calidad Inbound',
                'verbose_name_plural': 'Matrices de Calidad Inbound',
                'ordering': ['categoria', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Speech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='auditorias/audio/', validators=[calidad.models.validate_audio_file_extension])),
                ('resultado_json', models.JSONField(blank=True, help_text='Resultado de la transcripción de Speech-to-Text', null=True)),
                ('analisis_json', models.JSONField(blank=True, help_text='Resultado del análisis de calidad de la IA', null=True)),
                ('transcripcion', models.CharField(blank=True, help_text='Ruta del archivo de transcripción JSON', max_length=255, null=True)),
                ('duracion_segundos', models.FloatField(default=0, verbose_name='Duración en segundos')),
                ('tamano_archivo_mb', models.FloatField(default=0, verbose_name='Tamaño del archivo (MB)')),
                ('tokens_procesados', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tokens procesados')),
                ('tiempo_procesamiento', models.FloatField(blank=True, null=True, verbose_name='Tiempo de procesamiento (s)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('auditoria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='speech', to='calidad.auditoria')),
            ],
        ),
        migrations.CreateModel(
            name='UsoProcesamientoAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion_audio_segundos', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Duración del audio (segundos)')),
                ('tamano_archivo_mb', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tamaño del archivo (MB)')),
                ('fecha_transcripcion', models.DateTimeField(auto_now_add=True)),
                ('tiempo_transcripcion_segundos', models.FloatField(blank=True, null=True, verbose_name='Tiempo de transcripción (segundos)')),
                ('proveedor_transcripcion', models.CharField(default='replicate', max_length=50, verbose_name='Proveedor de transcripción')),
                ('costo_transcripcion', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='Costo de transcripción (USD)')),
                ('tokens_analisis', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tokens usados en análisis')),
                ('proveedor_analisis', models.CharField(default='deepseek', max_length=50, verbose_name='Proveedor de análisis')),
                ('costo_analisis', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='Costo de análisis (USD)')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('auditoria', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uso_procesamiento', to='calidad.auditoria')),
                ('speech', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uso_procesamiento', to='calidad.speech')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usos_procesamiento', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uso de Procesamiento de Audio',
                'verbose_name_plural': 'Usos de Procesamiento de Audio',
                'ordering': ['-fecha_transcripcion'],
            },
        ),
        migrations.CreateModel(
            name='DetalleAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cumple', models.BooleanField(default=False, help_text='Indica si el indicador cumple con los estándares de calidad', verbose_name='¿Cumple?')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones específicas sobre este indicador', null=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('auditoria', models.ForeignKey(help_text='Auditoría a la que pertenece esta respuesta', on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='calidad.auditoria', verbose_name='Auditoría')),
                ('indicador', models.ForeignKey(help_text='Indicador de calidad evaluado', on_delete=django.db.models.deletion.PROTECT, related_name='respuestas', to='calidad.matrizcalidad', verbose_name='Indicador')),
            ],
            options={
                'verbose_name': 'Detalle de Auditoría',
                'verbose_name_plural': 'Detalles de Auditorías',
                'unique_together': {('auditoria', 'indicador')},
            },
        ),
    ]
