# Generated by Django 5.2.1 on 2025-07-23 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrizcalidad',
            name='usuario_creacion',
            field=models.ForeignKey(help_text='Usuario que creó el registro', on_delete=django.db.models.deletion.PROTECT, related_name='matrices_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Creación'),
        ),
        migrations.DeleteModel(
            name='MatrizCalidadInbound',
        ),
    ]
