# Generated by Django 5.2.1 on 2025-07-23 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0002_alter_matrizcalidad_usuario_creacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditoria',
            name='area',
        ),
        migrations.RemoveField(
            model_name='auditoria',
            name='sede',
        ),
        migrations.RemoveField(
            model_name='auditoria',
            name='tipificacion',
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='tipo_monitoreo',
            field=models.CharField(choices=[('speech', 'Speech Analytics'), ('al_lado', 'Al Lado'), ('grabacion', 'Grabación')], help_text='Tipo de monitoreo realizado', max_length=20, verbose_name='Tipo de monitoreo'),
        ),
        migrations.AlterField(
            model_name='matrizcalidad',
            name='tipologia',
            field=models.CharField(choices=[('atencion_telefonica', 'Atencion Telefonica'), ('ofrecimiento_comercial', 'Ofrecimiento Comercial'), ('proceso_venta', 'Proceso de Venta')], help_text='Tipo de interacción o comunicación', max_length=50, verbose_name='Tipología'),
        ),
    ]
