# Generated by Django 5.2.1 on 2025-07-23 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0003_remove_auditoria_area_remove_auditoria_sede_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_respuesta', models.CharField(choices=[('compromiso_mejora', 'Compromiso de mejora'), ('aclaracion', 'Aclaración'), ('plan_accion', 'Plan de acción'), ('capacitacion', 'Solicitud de capacitación')], help_text='Categoría de la respuesta del asesor', max_length=20, verbose_name='Tipo de respuesta')),
                ('respuesta', models.TextField(help_text='Explicación, compromiso o plan de acción del asesor', verbose_name='Respuesta del asesor')),
                ('compromiso', models.TextField(blank=True, help_text='Compromiso específico del asesor para mejorar en este indicador', null=True, verbose_name='Compromiso de mejora')),
                ('fecha_compromiso', models.DateField(blank=True, help_text='Fecha en la que el asesor se compromete a implementar la mejora', null=True, verbose_name='Fecha límite del compromiso')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de respuesta'), ('respondido', 'Respondido'), ('en_seguimiento', 'En seguimiento'), ('cerrado', 'Cerrado')], default='pendiente', help_text='Estado actual de la respuesta', max_length=20, verbose_name='Estado')),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de respuesta')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('comentario_evaluador', models.TextField(blank=True, help_text='Comentarios del evaluador sobre la respuesta del asesor', null=True, verbose_name='Comentario del evaluador')),
                ('fecha_seguimiento', models.DateTimeField(blank=True, help_text='Fecha del último seguimiento por parte del evaluador', null=True, verbose_name='Fecha de seguimiento')),
                ('asesor', models.ForeignKey(help_text='Asesor que proporciona la respuesta', on_delete=django.db.models.deletion.PROTECT, related_name='respuestas_auditoria', to=settings.AUTH_USER_MODEL, verbose_name='Asesor')),
                ('auditoria', models.ForeignKey(help_text='Auditoría a la que pertenece esta respuesta', on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_asesor', to='calidad.auditoria', verbose_name='Auditoría')),
                ('detalle_auditoria', models.ForeignKey(help_text='Indicador específico al que se está respondiendo', on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_asesor', to='calidad.detalleauditoria', verbose_name='Detalle de Auditoría')),
                ('evaluador_seguimiento', models.ForeignKey(blank=True, help_text='Evaluador que hace seguimiento a la respuesta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimientos_respuestas', to=settings.AUTH_USER_MODEL, verbose_name='Evaluador de seguimiento')),
            ],
            options={
                'verbose_name': 'Respuesta de Auditoría',
                'verbose_name_plural': 'Respuestas de Auditorías',
                'ordering': ['-fecha_respuesta'],
                'unique_together': {('auditoria', 'detalle_auditoria', 'asesor')},
            },
        ),
    ]
