# Generated by Django 5.2.1 on 2025-07-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0004_respuestaauditoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='speech',
            name='minio_object_name',
            field=models.CharField(blank=True, help_text='Nombre del archivo en MinIO', max_length=255, null=True, verbose_name='Nombre del objeto en MinIO'),
        ),
        migrations.AddField(
            model_name='speech',
            name='minio_url',
            field=models.URLField(blank=True, help_text='URL pública del archivo en MinIO', max_length=500, null=True, verbose_name='URL de MinIO'),
        ),
        migrations.AddField(
            model_name='speech',
            name='subido_a_minio',
            field=models.BooleanField(default=False, help_text='Indica si el archivo fue subido exitosamente a MinIO', verbose_name='Subido a MinIO'),
        ),
    ]
