# Generated by Django 5.2.1 on 2025-07-30 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0005_speech_minio_object_name_speech_minio_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='tipo_monitoreo',
            field=models.CharField(choices=[('speech', 'Speech Analytics'), ('grabacion', 'Grabación')], help_text='Tipo de monitoreo realizado', max_length=20, verbose_name='Tipo de monitoreo'),
        ),
        migrations.AlterField(
            model_name='matrizcalidad',
            name='tipologia',
            field=models.CharField(choices=[('ECUF', 'ECUF'), ('ECN', 'ECN'), ('Estadistico', 'Estadistico')], help_text='Tipo de interacción o comunicación', max_length=50, verbose_name='Tipología'),
        ),
    ]
