# Generated by Django 5.2.1 on 2025-08-29 00:20

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calidad", "0006_alter_auditoria_tipo_monitoreo_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="speech",
            name="tipo_campana",
            field=models.CharField(
                choices=[
                    ("portabilidad", "Portabilidad"),
                    ("prepago", "Prepago"),
                    ("upgrade", "Upgrade"),
                ],
                default="portabilidad",
                help_text="Tipo de campaña para determinar la matriz de calidad a utilizar",
                max_length=20,
                verbose_name="Tipo de Campaña",
            ),
        ),
        migrations.CreateModel(
            name="AuditoriaPrepago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_telefono",
                    models.CharField(
                        help_text="Número de teléfono del cliente prepago",
                        max_length=20,
                        verbose_name="Número de teléfono",
                    ),
                ),
                (
                    "fecha_llamada",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Fecha en que se realizó la llamada prepago",
                        verbose_name="Fecha de la llamada",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True,
                        help_text="Observaciones generales de la auditoría prepago",
                        null=True,
                        verbose_name="Observaciones",
                    ),
                ),
                (
                    "tipo_monitoreo",
                    models.CharField(
                        choices=[
                            ("speech", "Speech Analytics"),
                            ("grabacion", "Grabación"),
                        ],
                        help_text="Tipo de monitoreo realizado para prepago",
                        max_length=20,
                        verbose_name="Tipo de monitoreo",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "puntaje_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Puntaje final de la auditoría prepago",
                        max_digits=5,
                        verbose_name="Puntaje Total",
                    ),
                ),
                (
                    "observaciones_tipificacion",
                    models.TextField(
                        blank=True,
                        help_text="Detalles sobre el logueo de la llamada prepago: tipificación, notas, etc.",
                        null=True,
                        verbose_name="Observaciones de Tipificación",
                    ),
                ),
                (
                    "puntaje_ia",
                    models.CharField(
                        blank=True,
                        help_text="Puntaje total de la evaluación de IA para prepago",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "resumen_ia",
                    models.TextField(
                        blank=True,
                        help_text="Resumen de la evaluación de calidad generado por IA para prepago",
                        null=True,
                    ),
                ),
                (
                    "agente",
                    models.ForeignKey(
                        help_text="Agente que está siendo evaluado en campaña prepago",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="auditorias_prepago_recibidas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Agente evaluado",
                    ),
                ),
                (
                    "evaluador",
                    models.ForeignKey(
                        help_text="Persona que realiza la evaluación prepago",
                        limit_choices_to={"groups__name": "Calidad"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="auditorias_prepago_realizadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Evaluador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Auditoría Prepago",
                "verbose_name_plural": "Auditorías Prepago",
                "ordering": ["-fecha_llamada"],
                "permissions": [
                    ("puede_ver_auditorias_prepago", "Puede ver auditorías prepago"),
                    (
                        "puede_editar_auditorias_prepago",
                        "Puede editar auditorías prepago",
                    ),
                    (
                        "puede_eliminar_auditorias_prepago",
                        "Puede eliminar auditorías prepago",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditoriaUpgrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_telefono",
                    models.CharField(
                        help_text="Número de teléfono del cliente upgrade",
                        max_length=20,
                        verbose_name="Número de teléfono",
                    ),
                ),
                (
                    "fecha_llamada",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Fecha en que se realizó la llamada upgrade",
                        verbose_name="Fecha de la llamada",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True,
                        help_text="Observaciones generales de la auditoría upgrade",
                        null=True,
                        verbose_name="Observaciones",
                    ),
                ),
                (
                    "tipo_monitoreo",
                    models.CharField(
                        choices=[
                            ("speech", "Speech Analytics"),
                            ("grabacion", "Grabación"),
                        ],
                        help_text="Tipo de monitoreo realizado para upgrade",
                        max_length=20,
                        verbose_name="Tipo de monitoreo",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "puntaje_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Puntaje final de la auditoría upgrade",
                        max_digits=5,
                        verbose_name="Puntaje Total",
                    ),
                ),
                (
                    "observaciones_tipificacion",
                    models.TextField(
                        blank=True,
                        help_text="Detalles sobre el logueo de la llamada upgrade: tipificación, notas, etc.",
                        null=True,
                        verbose_name="Observaciones de Tipificación",
                    ),
                ),
                (
                    "puntaje_ia",
                    models.CharField(
                        blank=True,
                        help_text="Puntaje total de la evaluación de IA para upgrade",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "resumen_ia",
                    models.TextField(
                        blank=True,
                        help_text="Resumen de la evaluación de calidad generado por IA para upgrade",
                        null=True,
                    ),
                ),
                (
                    "agente",
                    models.ForeignKey(
                        help_text="Agente que está siendo evaluado en campaña upgrade",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="auditorias_upgrade_recibidas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Agente evaluado",
                    ),
                ),
                (
                    "evaluador",
                    models.ForeignKey(
                        help_text="Persona que realiza la evaluación upgrade",
                        limit_choices_to={"groups__name": "Calidad"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="auditorias_upgrade_realizadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Evaluador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Auditoría Upgrade",
                "verbose_name_plural": "Auditorías Upgrade",
                "ordering": ["-fecha_llamada"],
                "permissions": [
                    ("puede_ver_auditorias_upgrade", "Puede ver auditorías upgrade"),
                    (
                        "puede_editar_auditorias_upgrade",
                        "Puede editar auditorías upgrade",
                    ),
                    (
                        "puede_eliminar_auditorias_upgrade",
                        "Puede eliminar auditorías upgrade",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MatrizCalidadPrepago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipologia",
                    models.CharField(
                        choices=[
                            ("RECARGA", "Recarga"),
                            ("ACTIVACION", "Activación"),
                            ("CONSULTA_SALDO", "Consulta de Saldo"),
                            ("CAMBIO_PLAN", "Cambio de Plan"),
                            ("SOPORTE_TECNICO", "Soporte Técnico"),
                        ],
                        help_text="Tipo de interacción específica para servicios prepago",
                        max_length=50,
                        verbose_name="Tipología Prepago",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        help_text="Nombre de la categoría del indicador para prepago",
                        max_length=100,
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "indicador",
                    models.CharField(
                        help_text="Descripción del indicador de calidad para prepago",
                        max_length=255,
                        verbose_name="Indicador",
                    ),
                ),
                (
                    "ponderacion",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Peso del indicador en la evaluación total (0.01 - 100)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0.01),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Ponderación (%)",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Actualización"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "usuario_creacion",
                    models.ForeignKey(
                        help_text="Usuario que creó el registro",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="matrices_prepago_creadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario de Creación",
                    ),
                ),
            ],
            options={
                "verbose_name": "Matriz de Calidad Prepago",
                "verbose_name_plural": "Matrices de Calidad Prepago",
                "ordering": ["categoria", "id"],
            },
        ),
        migrations.CreateModel(
            name="DetalleAuditoriaPrepago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cumple",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si el indicador cumple con los estándares de calidad prepago",
                        verbose_name="¿Cumple?",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True,
                        help_text="Observaciones específicas sobre este indicador prepago",
                        null=True,
                        verbose_name="Observaciones",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "auditoria",
                    models.ForeignKey(
                        help_text="Auditoría prepago a la que pertenece esta respuesta",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respuestas_prepago",
                        to="calidad.auditoriaprepago",
                        verbose_name="Auditoría Prepago",
                    ),
                ),
                (
                    "indicador",
                    models.ForeignKey(
                        help_text="Indicador de calidad prepago evaluado",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="respuestas_prepago",
                        to="calidad.matrizcalidadprepago",
                        verbose_name="Indicador Prepago",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Auditoría Prepago",
                "verbose_name_plural": "Detalles de Auditorías Prepago",
                "unique_together": {("auditoria", "indicador")},
            },
        ),
        migrations.CreateModel(
            name="MatrizCalidadUpgrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipologia",
                    models.CharField(
                        choices=[
                            ("UPGRADE_PLAN", "Upgrade de Plan"),
                            ("UPGRADE_EQUIPO", "Upgrade de Equipo"),
                            ("MIGRACION_POSTPAGO", "Migración a Postpago"),
                            ("SERVICIOS_ADICIONALES", "Servicios Adicionales"),
                            ("RETENCION", "Retención"),
                        ],
                        help_text="Tipo de interacción específica para servicios de upgrade",
                        max_length=50,
                        verbose_name="Tipología Upgrade",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        help_text="Nombre de la categoría del indicador para upgrade",
                        max_length=100,
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "indicador",
                    models.CharField(
                        help_text="Descripción del indicador de calidad para upgrade",
                        max_length=255,
                        verbose_name="Indicador",
                    ),
                ),
                (
                    "ponderacion",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Peso del indicador en la evaluación total (0.01 - 100)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0.01),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Ponderación (%)",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Actualización"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "usuario_creacion",
                    models.ForeignKey(
                        help_text="Usuario que creó el registro",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="matrices_upgrade_creadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario de Creación",
                    ),
                ),
            ],
            options={
                "verbose_name": "Matriz de Calidad Upgrade",
                "verbose_name_plural": "Matrices de Calidad Upgrade",
                "ordering": ["categoria", "id"],
            },
        ),
        migrations.CreateModel(
            name="DetalleAuditoriaUpgrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cumple",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si el indicador cumple con los estándares de calidad upgrade",
                        verbose_name="¿Cumple?",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True,
                        help_text="Observaciones específicas sobre este indicador upgrade",
                        null=True,
                        verbose_name="Observaciones",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "auditoria",
                    models.ForeignKey(
                        help_text="Auditoría upgrade a la que pertenece esta respuesta",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respuestas_upgrade",
                        to="calidad.auditoriaupgrade",
                        verbose_name="Auditoría Upgrade",
                    ),
                ),
                (
                    "indicador",
                    models.ForeignKey(
                        help_text="Indicador de calidad upgrade evaluado",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="respuestas_upgrade",
                        to="calidad.matrizcalidadupgrade",
                        verbose_name="Indicador Upgrade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Auditoría Upgrade",
                "verbose_name_plural": "Detalles de Auditorías Upgrade",
                "unique_together": {("auditoria", "indicador")},
            },
        ),
        migrations.CreateModel(
            name="RespuestaAuditoriaPrepago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_respuesta",
                    models.CharField(
                        choices=[
                            ("explicacion", "Explicación"),
                            ("desacuerdo", "Desacuerdo"),
                            ("plan_mejora", "Plan de Mejora"),
                            ("capacitacion", "Solicitud de Capacitación"),
                            ("aclaracion", "Solicitud de Aclaración"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de respuesta",
                    ),
                ),
                (
                    "respuesta",
                    models.TextField(
                        help_text="Respuesta detallada del asesor",
                        verbose_name="Respuesta",
                    ),
                ),
                (
                    "compromiso",
                    models.TextField(
                        blank=True,
                        help_text="Compromiso específico de mejora (opcional)",
                        null=True,
                        verbose_name="Compromiso de mejora",
                    ),
                ),
                (
                    "fecha_compromiso",
                    models.DateField(
                        blank=True,
                        help_text="Fecha en la que se compromete a implementar la mejora",
                        null=True,
                        verbose_name="Fecha límite del compromiso",
                    ),
                ),
                (
                    "fecha_respuesta",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de respuesta"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "asesor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="respuestas_auditorias_prepago",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Asesor",
                    ),
                ),
                (
                    "auditoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respuestas_asesor_prepago",
                        to="calidad.auditoriaprepago",
                        verbose_name="Auditoría Prepago",
                    ),
                ),
                (
                    "detalle_auditoria",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respuesta_asesor_prepago",
                        to="calidad.detalleauditoriaprepago",
                        verbose_name="Detalle de Auditoría Prepago",
                    ),
                ),
            ],
            options={
                "verbose_name": "Respuesta de Auditoría Prepago",
                "verbose_name_plural": "Respuestas de Auditorías Prepago",
                "ordering": ["-fecha_respuesta"],
            },
        ),
        migrations.CreateModel(
            name="RespuestaAuditoriaUpgrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_respuesta",
                    models.CharField(
                        choices=[
                            ("explicacion", "Explicación"),
                            ("desacuerdo", "Desacuerdo"),
                            ("plan_mejora", "Plan de Mejora"),
                            ("capacitacion", "Solicitud de Capacitación"),
                            ("aclaracion", "Solicitud de Aclaración"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de respuesta",
                    ),
                ),
                (
                    "respuesta",
                    models.TextField(
                        help_text="Respuesta detallada del asesor",
                        verbose_name="Respuesta",
                    ),
                ),
                (
                    "compromiso",
                    models.TextField(
                        blank=True,
                        help_text="Compromiso específico de mejora (opcional)",
                        null=True,
                        verbose_name="Compromiso de mejora",
                    ),
                ),
                (
                    "fecha_compromiso",
                    models.DateField(
                        blank=True,
                        help_text="Fecha en la que se compromete a implementar la mejora",
                        null=True,
                        verbose_name="Fecha límite del compromiso",
                    ),
                ),
                (
                    "fecha_respuesta",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de respuesta"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "asesor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="respuestas_auditorias_upgrade",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Asesor",
                    ),
                ),
                (
                    "auditoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respuestas_asesor_upgrade",
                        to="calidad.auditoriaupgrade",
                        verbose_name="Auditoría Upgrade",
                    ),
                ),
                (
                    "detalle_auditoria",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respuesta_asesor_upgrade",
                        to="calidad.detalleauditoriaupgrade",
                        verbose_name="Detalle de Auditoría Upgrade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Respuesta de Auditoría Upgrade",
                "verbose_name_plural": "Respuestas de Auditorías Upgrade",
                "ordering": ["-fecha_respuesta"],
            },
        ),
    ]
