# Generated by Django 5.2.1 on 2025-08-29 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calidad", "0007_speech_tipo_campana_auditoriaprepago_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matrizcalidadprepago",
            name="tipologia",
            field=models.CharField(
                choices=[
                    ("ECUF", "ECUF"),
                    ("ECN", "ECN"),
                    ("Estadistico", "Estadístico"),
                ],
                help_text="Tipo de interacción específica para servicios prepago",
                max_length=50,
                verbose_name="Tipología Prepago",
            ),
        ),
        migrations.AlterField(
            model_name="matrizcalidadupgrade",
            name="tipologia",
            field=models.CharField(
                choices=[
                    ("ECUF", "ECUF"),
                    ("ECN", "ECN"),
                    ("Estadistico", "Estadístico"),
                ],
                help_text="Tipo de interacción específica para servicios de upgrade",
                max_length=50,
                verbose_name="Tipología Upgrade",
            ),
        ),
    ]
