# Generated by Django 4.2.23 on 2025-11-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calidad", "0007_speech_tipo_campana_auditoriaprepago_and_more"),
        ("calidad", "0008_alter_matrizcalidadprepago_tipologia_and_more"),
        ("calidad", "0010_create_auditoriaupgrade_if_missing"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditoriaupgrade",
            name="duracion_segundos",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="auditoriaupgrade",
            name="minio_object_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="auditoriaupgrade",
            name="minio_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="auditoriaupgrade",
            name="subido_a_minio",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="auditoriaupgrade",
            name="tamano_archivo_mb",
            field=models.FloatField(default=0),
        ),
    ]
