# Generated by Django 4.2.23 on 2025-11-29 20:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calidad", "0015_auditoriaupgrade_transcripcion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matrizcalidad",
            name="ponderacion",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Peso del indicador en la evaluación total (-100 a 100)",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(-100),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Ponderación (%)",
            ),
        ),
    ]
