# Generated by Django 5.2.1 on 2025-08-04 03:12

import django.db.models.deletion
import tarjeta_plata.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteTarjetaPlata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50, unique=True, verbose_name='Item')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('factibilidad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], max_length=10, verbose_name='Factibilidad')),
                ('tipo', models.CharField(choices=[('nuevo', 'Nuevo'), ('existente', 'Existente')], max_length=15, verbose_name='Tipo')),
                ('rfc', models.CharField(max_length=13, verbose_name='RFC')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, verbose_name='Género')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Cliente Tarjeta Plata',
                'verbose_name_plural': 'Clientes Tarjeta Plata',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='VentaTarjetaPlata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_preap', models.CharField(max_length=50, unique=True, verbose_name='ID PreAp')),
                ('item', models.CharField(max_length=50, verbose_name='Item')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('ine', models.CharField(max_length=20, verbose_name='INE')),
                ('rfc', models.CharField(max_length=13, verbose_name='RFC')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('codigo_postal', models.CharField(max_length=10, verbose_name='Código Postal')),
                ('estado_venta', models.CharField(choices=[('nueva', 'Nueva'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='nueva', max_length=20, verbose_name='Estado Venta')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('fecha_revision', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Revisión')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_tarjeta_plata_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Agente')),
                ('backoffice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_tarjeta_plata_revisadas', to=settings.AUTH_USER_MODEL, verbose_name='Backoffice')),
                ('cliente_base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tarjeta_plata.clientetarjetaplata', verbose_name='Cliente Base')),
            ],
            options={
                'verbose_name': 'Venta Tarjeta Plata',
                'verbose_name_plural': 'Ventas Tarjeta Plata',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='GestionBackofficeTarjetaPlata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(choices=[('nueva', 'Nueva'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], max_length=20, verbose_name='Estado Anterior')),
                ('estado_nuevo', models.CharField(choices=[('nueva', 'Nueva'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], max_length=20, verbose_name='Estado Nuevo')),
                ('comentario', models.TextField(verbose_name='Comentario')),
                ('fecha_gestion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Gestión')),
                ('backoffice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestiones_tarjeta_plata', to=settings.AUTH_USER_MODEL, verbose_name='Backoffice')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestiones_backoffice', to='tarjeta_plata.ventatarjetaplata', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Gestión Backoffice Tarjeta Plata',
                'verbose_name_plural': 'Gestiones Backoffice Tarjeta Plata',
                'ordering': ['-fecha_gestion'],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaBackofficeTarjetaPlata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_auditoria_back', models.CharField(default=tarjeta_plata.models.AuditoriaBackofficeTarjetaPlata.generar_id_auditoria, max_length=50, unique=True, verbose_name='ID Auditoría Back')),
                ('call_review', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], max_length=2, verbose_name='Call Review')),
                ('call_upload', models.FileField(blank=True, null=True, upload_to='tarjeta_plata/call_uploads/', verbose_name='Call Upload')),
                ('observaciones_auditoria', models.TextField(blank=True, null=True, verbose_name='Observaciones de Auditoría')),
                ('fecha_auditoria', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Auditoría')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('auditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_tarjeta_plata', to=settings.AUTH_USER_MODEL, verbose_name='Auditor')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias_backoffice', to='tarjeta_plata.ventatarjetaplata', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Auditoría Backoffice Tarjeta Plata',
                'verbose_name_plural': 'Auditorías Backoffice Tarjeta Plata',
                'ordering': ['-fecha_auditoria'],
            },
        ),
    ]
