# Generated by Django 5.2.1 on 2025-08-04 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjeta_plata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientetarjetaplata',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
    ]
