# Generated by Django 5.2.1 on 2025-08-04 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjeta_plata', '0002_alter_clientetarjetaplata_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventatarjetaplata',
            name='id_preap',
            field=models.CharField(help_text='ID de preaprobación obtenido de la plataforma del banco', max_length=50, unique=True, verbose_name='ID PreAp'),
        ),
    ]
