# Generated by Django 5.2.1 on 2025-08-04 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjeta_plata', '0003_alter_ventatarjetaplata_id_preap'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestionbackofficetarjetaplata',
            name='archivo_llamada',
            field=models.FileField(blank=True, help_text='Archivo de audio de la llamada de venta (opcional)', null=True, upload_to='tarjeta_plata/llamadas/', verbose_name='Archivo de Llamada'),
        ),
    ]
