# Generated by Django 5.2.1 on 2025-08-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjeta_plata', '0004_gestionbackofficetarjetaplata_archivo_llamada'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventatarjetaplata',
            name='dn',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='DN'),
        ),
        migrations.AddField(
            model_name='ventatarjetaplata',
            name='entrega',
            field=models.CharField(blank=True, choices=[('domicilio', 'Domicilio'), ('centro_comercial', 'Centro Comercial')], max_length=20, null=True, verbose_name='Tipo de Entrega'),
        ),
        migrations.AddField(
            model_name='ventatarjetaplata',
            name='estado_republica',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado República'),
        ),
        migrations.AddField(
            model_name='ventatarjetaplata',
            name='ingreso_mensual_cliente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Ingreso Mensual Cliente'),
        ),
        migrations.AddField(
            model_name='ventatarjetaplata',
            name='resultado',
            field=models.CharField(blank=True, choices=[('venta_bbd', 'Venta BBD'), ('venta_referidos', 'Venta Referidos'), ('rechazada', 'Rechazada'), ('venta_md', 'Venta MD'), ('otro', 'Otro')], max_length=20, null=True, verbose_name='Resultado'),
        ),
        migrations.AddField(
            model_name='ventatarjetaplata',
            name='usuario_c8',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuario C8'),
        ),
    ]
